- name: install git switcher
  copy:
    src: git-switch-remote
    dest: "{{ user_bin_dir }}/git-switch-remote"
    mode: 0755

- name: install base git configs
  template:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
  with_items:
    - gitignore
    - gitconfig
