alias sl='ls'
alias trains='/usr/bin/sl'
alias grep='grep --colour=auto'
alias cls='clear'
alias gpl='git pull'
alias gps='git push'
alias gc='git commit -am'
alias ga='git add .'
alias gb='git branch'
alias gs='git status'
alias rm='rm -rf'
alias ':w'='echo "Need to open vim first..."'
alias ':q'='echo "Need to open vim first..."'
alias ls='/bin/ls --color=tty -lh'
alias d='docker'
alias dc='docker-compose'
alias tmux='tmux -2'
