---
- name: install
  package:
    name:
      - wget
      - tmux
      - sl
      - mactex
      - imagemagick
      - watchman
      - htop
      - exiftool
      - jq
      - yq
      - ffmpeg-full
      - nmap
      - gh
      - iperf3
    state: present

- include_tasks: plistwatch.yaml
