---
- name: install
  package:
    name:
      - wget
      - tmux
      - sl
      - mactex
      - imagemagick
      - watchman
      - htop
      - exiftool
      - jq
      - yq
    state: present

- include_tasks: plistwatch.yaml
